from __future__ import annotations

from datetime import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Image as RLImage,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.config import Settings
from app.utils.display_labels import prediction_display_label
from app.utils.json_utils import load_json

_STYLES = getSampleStyleSheet()
_TITLE_STYLE = ParagraphStyle("PRSVTitle", parent=_STYLES["Title"], fontSize=20, spaceAfter=4)
_SUBTITLE_STYLE = ParagraphStyle("PRSVSubtitle", parent=_STYLES["Normal"], fontSize=10, textColor=colors.grey)
_HEADING_STYLE = ParagraphStyle("PRSVHeading", parent=_STYLES["Heading2"], spaceBefore=14, spaceAfter=6)
_BODY_STYLE = ParagraphStyle("PRSVBody", parent=_STYLES["Normal"], fontSize=10, leading=14)


def _prediction_color(prediction: str) -> colors.Color:
    return colors.HexColor("#c0392b") if (prediction or "").lower() != "healthy" else colors.HexColor("#1e8449")


def _logo_header(settings: Settings, title_text: str):
    """
    Builds a logo + title row for the top of a PDF report. Falls back to a
    plain title (no logo) if the logo asset is missing, so report generation
    never breaks because of a missing image file.
    """
    logo_path = settings.models_dir.parent / "app" / "static" / "img" / "logo-icon.png"
    title_para = Paragraph(title_text, _TITLE_STYLE)

    if not logo_path.exists():
        return [title_para]

    try:
        logo_img = RLImage(str(logo_path), width=16 * mm, height=16 * mm)
        header_table = Table([[logo_img, title_para]], colWidths=[20 * mm, 150 * mm])
        header_table.setStyle(
            TableStyle(
                [
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("LEFTPADDING", (0, 0), (0, 0), 0),
                    ("LEFTPADDING", (1, 0), (1, 0), 8),
                    ("TOPPADDING", (0, 0), (-1, -1), 0),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
                ]
            )
        )
        return [header_table]
    except Exception:  # noqa: BLE001 - a broken logo file should never block report generation
        return [title_para]


def _disclaimer_paragraph() -> Paragraph:
    return Paragraph(
        "This report is generated by an automated research/demo system and is not a substitute for "
        "professional agricultural diagnosis. For severe or uncertain cases, consult a local agricultural "
        "extension officer.",
        ParagraphStyle("Disclaimer", parent=_BODY_STYLE, fontSize=8, textColor=colors.grey),
    )


def generate_image_report_pdf(settings: Settings, run_id: str, image_id: str, image_dir: Path) -> Path:
    prediction_data = load_json(image_dir / "prediction.json") if (image_dir / "prediction.json").exists() else {}
    severity_data = load_json(image_dir / "severity.json") if (image_dir / "severity.json").exists() else {}
    features_data = load_json(image_dir / "features.json") if (image_dir / "features.json").exists() else {}
    rag_data = load_json(image_dir / "rag.json") if (image_dir / "rag.json").exists() else {}

    prediction = prediction_data.get("prediction", "Unknown")
    display_prediction = prediction_display_label(prediction)
    confidence = prediction_data.get("confidence", 0.0)
    severity_label = severity_data.get("severity_label", "Unknown")
    severity_score = severity_data.get("severity_score", 0.0)
    feature_values = features_data.get("feature_values", {})
    farmer_explanation = rag_data.get("farmer_friendly_explanation", "")
    advisory_notes = rag_data.get("advisory_notes", [])

    reports_dir = settings.reports_dir
    reports_dir.mkdir(parents=True, exist_ok=True)
    output_path = reports_dir / f"prsv_report_{image_id}.pdf"

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        topMargin=18 * mm,
        bottomMargin=16 * mm,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
    )

    story = []
    story.extend(_logo_header(settings, "PRSV Analyzer - Diagnostic Report"))
    story.append(
        Paragraph(
            f"Run: {run_id} &nbsp;&middot;&nbsp; Image: {image_id} &nbsp;&middot;&nbsp; "
            f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            _SUBTITLE_STYLE,
        )
    )
    story.append(Spacer(1, 10))

    original_image_path = image_dir / "original.jpg"
    if not original_image_path.exists():
        candidates = list(image_dir.glob("original.*"))
        if candidates:
            original_image_path = candidates[0]

    if original_image_path.exists():
        try:
            story.append(RLImage(str(original_image_path), width=80 * mm, height=80 * mm, kind="proportional"))
            story.append(Spacer(1, 8))
        except Exception:  # noqa: BLE001 - a broken thumbnail should never block the report
            pass

    result_table = Table(
        [
            ["Prediction", display_prediction],
            ["Confidence", f"{confidence * 100:.1f}%"],
            ["Severity", f"{severity_label} ({severity_score:.1f}%)"],
        ],
        colWidths=[45 * mm, 120 * mm],
    )
    result_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f2f2f2")),
                ("TEXTCOLOR", (1, 0), (1, 0), _prediction_color(prediction)),
                ("FONTNAME", (1, 0), (1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#dddddd")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.append(result_table)

    if farmer_explanation:
        story.append(Paragraph("Explanation", _HEADING_STYLE))
        story.append(Paragraph(farmer_explanation, _BODY_STYLE))

    if advisory_notes:
        story.append(Paragraph("Recommended Actions", _HEADING_STYLE))
        for note in advisory_notes:
            story.append(Paragraph(f"&bull; {note}", _BODY_STYLE))

    if feature_values:
        story.append(Paragraph("Image-Derived Features", _HEADING_STYLE))
        feature_rows = [["Feature", "Value"]] + [
            [name.replace("_", " ").title(), f"{value:.4f}"] for name, value in feature_values.items()
        ]
        feature_table = Table(feature_rows, colWidths=[85 * mm, 80 * mm])
        feature_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2c3e50")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#dddddd")),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f7f7f7")]),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ]
            )
        )
        story.append(feature_table)

    story.append(Spacer(1, 16))
    story.append(_disclaimer_paragraph())

    doc.build(story)
    return output_path


def generate_run_report_pdf(settings: Settings, run_id: str, run_dir: Path) -> Path:
    summary = load_json(run_dir / "batch_summary.json")

    reports_dir = settings.reports_dir
    reports_dir.mkdir(parents=True, exist_ok=True)
    output_path = reports_dir / f"prsv_run_report_{run_id}.pdf"

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        topMargin=18 * mm,
        bottomMargin=16 * mm,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
    )

    story = []
    story.extend(_logo_header(settings, "PRSV Analyzer - Batch Run Report"))
    story.append(
        Paragraph(
            f"Run: {run_id} &nbsp;&middot;&nbsp; Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            _SUBTITLE_STYLE,
        )
    )
    story.append(Spacer(1, 10))

    summary_table = Table(
        [
            ["Total Images", str(summary.get("total_images", 0))],
            ["Processed", str(summary.get("processed_images", 0))],
            ["Failed", str(summary.get("failed_images", 0))],
            ["Healthy", str(summary.get("healthy_count", 0))],
            ["PRSV Suspected", str(summary.get("diseased_count", 0))],
            ["Average Confidence", f"{summary.get('average_confidence', 0) * 100:.1f}%"],
            ["Average Infection %", f"{summary.get('average_infection_percentage', 0):.1f}%"],
        ],
        colWidths=[60 * mm, 100 * mm],
    )
    summary_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f2f2f2")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#dddddd")),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.append(summary_table)

    results = summary.get("results", [])
    if results:
        story.append(Paragraph("Per-Image Results", _HEADING_STYLE))
        rows = [["Filename", "Prediction", "Confidence", "Severity"]]
        for item in results:
            rows.append(
                [
                    item.get("filename", ""),
                    prediction_display_label(item.get("prediction", "")),
                    f"{item.get('confidence', 0) * 100:.1f}%",
                    item.get("severity_label", ""),
                ]
            )
        results_table = Table(rows, colWidths=[60 * mm, 40 * mm, 30 * mm, 40 * mm], repeatRows=1)
        results_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2c3e50")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#dddddd")),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f7f7f7")]),
                    ("FONTSIZE", (0, 1), (-1, -1), 8),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ]
            )
        )
        story.append(results_table)

    story.append(Spacer(1, 16))
    story.append(_disclaimer_paragraph())

    doc.build(story)
    return output_path
